name: Watch for New YAML Files

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  notify_new_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Restore notification history cache
        id: cache
        uses: actions/cache@v4
        with:
          path: .notified/history.txt
          key: notification-history-${{ hashFiles('.notified/history.txt') }}
          restore-keys: |
            notification-history-

      - name: Setup environment
        run: |
          mkdir -p .notified
          touch .notified/history.txt

      - name: Get latest commit SHA
        id: get_sha
        run: |
          SHA=$(curl -s https://api.github.com/repos/anderwordzkkkz/nuclei-templates/commits/main | jq -r .sha)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Load previous SHA
        id: load_sha
        run: |
          if [ -f .last_sha ]; then
            echo "old_sha=$(cat .last_sha)" >> $GITHUB_OUTPUT
          else
            echo "old_sha=" >> $GITHUB_OUTPUT
          fi

      - name: Compare and get added YAMLs
        id: compare
        run: |
          OLD_SHA="${{ steps.load_sha.outputs.old_sha }}"
          NEW_SHA="${{ steps.get_sha.outputs.sha }}"

          if [ -z "$OLD_SHA" ]; then
            echo "$NEW_SHA" > .last_sha
            echo "count=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [ "$OLD_SHA" = "$NEW_SHA" ]; then
            echo "No new commits"
            echo "count=0" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "$NEW_SHA" > .last_sha

          curl -s https://api.github.com/repos/anderwordzkkkz/nuclei-templates/compare/$OLD_SHA...$NEW_SHA \
          | jq -r '.files[] | select(.status == "added") | .filename' \
          | grep '\.yaml$' > new_templates.txt || true

          count=$(wc -l < new_templates.txt)
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Filter truly new files
        run: |
          # Clean the history file
          sed -i '/^$/d' .notified/history.txt
          sort -u .notified/history.txt -o .notified/history.txt

          # Find only new files that haven't been notified before
          comm -23 <(sort new_templates.txt) <(sort .notified/history.txt) > only_new.txt || true

      - name: Send Discord Notification
        if: success() && steps.compare.outputs.count != '0' && fileExists('only_new.txt') && fileSize('only_new.txt') > 0
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          MESSAGE="🧩 **New Nuclei YAML Templates Added!**"
          while read FILE; do
            MESSAGE="$MESSAGE\n- \`$FILE\` <https://github.com/anderwordzkkkz/nuclei-templates/blob/main/$FILE>"
          done < only_new.txt

          echo -e "$MESSAGE" | jq -Rs '{content: .}' > payload.json
          curl -H "Content-Type: application/json" -X POST -d @payload.json "$DISCORD_WEBHOOK"

          # Update history with newly notified files
          cat only_new.txt >> .notified/history.txt
          sort -u .notified/history.txt -o .notified/history.txt

      - name: Save notification history
        uses: actions/cache@v4
        with:
          path: .notified/history.txt
          key: notification-history-${{ hashFiles('.notified/history.txt') }}
